---
version: '1'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "18123:8123"
      - "19000:9000"

  otel-clickhouse-datagen:
    build: ./
    container_name: otel-clickhouse-datagen
    ports:
      - "8088:8088"
      - "8888:8888"
      - "13133:13133"
    volumes:
      - ./config.yml:/etc/config.yml
      - ./generator-config.yml:/etc/generator-config.yml
    environment:
      - TOPO_FILE=
    depends_on:
      - clickhouse-server